# Generated by Django 4.2.1 on 2023-08-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="product", unique_together=set(),),
    ]
