# Generated by Django 4.2.1 on 2023-08-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0002_alter_vegetable_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vegetable",
            name="item_type",
            field=models.CharField(default=0, max_length=100),
        ),
    ]
