# Generated by Django 4.2.1 on 2023-08-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0003_alter_vegetable_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vegetable",
            name="item_type",
            field=models.CharField(default="---", max_length=100),
        ),
    ]
